language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - curl
    - freeglut3-dev
    - g++
    - g++-aarch64-linux-gnu
    - g++-arm-linux-gnueabihf
    - gperf
    - libbz2-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libgl1-mesa-dri
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libosmesa6-dev
    - libssl-dev
    - libxmu-dev
    - libxmu6
    - python-pip
    - python-virtualenv
    - xorg-dev
    # for Android:
    - ant
    - expect
    - lib32gcc1
    - lib32stdc++6
    - lib32z1
    - openjdk-7-jdk

cache:
  directories:
    - .cargo
    - .servo
    - $HOME/.ccache

env:
  global:
  - CCACHE=/usr/bin/ccache
  - secure: "Sd0FfHW7FZVAs4/95EcZUUNoWdFPM0ELn1DSHyY6eJNqptXm112hqU+AnicohuDPq4BSOgoeNVb+erROYld2cOIzuU+icR5yMdBG08X488B2Cw3366Xvls9al2HOB0IUoetv9MZB/ZldxkiPBwlGbcFG7ScnQZEZY31gS4aZdzqk2EjkHlIMJ9J4v0ORrl69BQc8KyHgprMGZ+C1SkD2aznJKAsTE+4qAJMLaCF0zYvgGaB3g6qLU5O1sdG3mN59vQXmWnumeNWzWm6fUC1CvHgJggElJ8wE6oTDOT4659PnZX5fbRWfO5bjYqH9VEcymGAP+lwOTWcg/T/btOvJuPog7gOkO4HGNBZir9oeEUpQ1xGFyDYLK84jl2nTAO5IPAGcNbWAJplQ5DLxvt24hRKCW4B2xD3Xm/bgPeOumVP13ad5SlhPZSgeBt/xLXrYd4k2J+MzBwU+Bh5ES/BFF4lJoDjmTsh/7GbrIrtjp8fPsNMNcn97EpFUK7akeHOsonCeT5P0opcEXfyXW/IjlUI5Ml5lrswR+LbLCs6MY6OQf1LRLyt7U1rZh+jtbE7aoHcfvNj2Fz6Gv5THkLxgbCMbODdN2B7cuNFExjA9S1euxz/1QUmv2QKrjQLbadPh8qrCoBdCcZzlvWQn06IHR4UCNVlCz8LowUTHqJXmDAI="

matrix:
  # Clear the whole matrix
  exclude:
  - os: linux
  - os: osx


  include:
  # Source only
  - os: linux
    env:
    - BUILD_TARGET=source
    script:
    - git clone https://github.com/servo/servo --depth=1
    - export ASSET_NAME=servo_source_$(date '+%Y-%m-%d').tgz
    - tar czf $ASSET_NAME servo --exclude-vcs --exclude='tests'
    - mv $ASSET_NAME servo/
    after_success:
    - ./upload_to_github.py

  # x86_64
  - os: linux
    env:
    - BUILD_TARGET=x86_64-unknown-linux-gnu TRIPLET=x86_64-linux-gnu

  # ARM
  - os: linux
    env:
    - BUILD_TARGET=arm-unknown-linux-gnueabihf TRIPLET=arm-linux-gnueabihf
    - PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
    - EXPAT_NO_PKG_CONFIG=1 FREETYPE2_NO_PKG_CONFIG=1 FONTCONFIG_NO_PKG_CONFIG=1
    before_script:
    - mkdir $HOME/bin
    - for f in /usr/bin/arm-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
    # download and link system libs
    - wget https://servo-rust.s3.amazonaws.com/ARM/armhf-trusty-libs.tgz
    - mkdir rootfs-trusty-armhf
    - tar xzf armhf-trusty-libs.tgz -C rootfs-trusty-armhf
    - sudo ln -s $(pwd)/rootfs-trusty-armhf/usr/include/arm-linux-gnueabihf /usr/include/arm-linux-gnueabihf
    - sudo ln -s $(pwd)/rootfs-trusty-armhf/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf
    - sudo ln -s $(pwd)/rootfs-trusty-armhf/lib/arm-linux-gnueabihf /lib/arm-linux-gnueabihf

  # AArch64
  - os: linux
    env:
    - BUILD_TARGET=aarch64-unknown-linux-gnu TRIPLET=aarch64-linux-gnu
    - PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
    - EXPAT_NO_PKG_CONFIG=1 FREETYPE2_NO_PKG_CONFIG=1 FONTCONFIG_NO_PKG_CONFIG=1
    before_script:
    - mkdir $HOME/bin
    - for f in /usr/bin/aarch64-linux-*; do f2=$(basename $f); ln -s $f $HOME/bin/${f2/-linux/-unknown-linux}; done
    # download and link system libs
    - wget https://servo-rust.s3.amazonaws.com/ARM/arm64-trusty-libs.tgz
    - mkdir rootfs-trusty-arm64
    - tar xzf arm64-trusty-libs.tgz -C rootfs-trusty-arm64
    - sudo ln -s $(pwd)/rootfs-trusty-arm64/usr/include/aarch64-linux-gnu /usr/include/aarch64-linux-gnu
    - sudo ln -s $(pwd)/rootfs-trusty-arm64/usr/lib/aarch64-linux-gnu /usr/lib/aarch64-linux-gnu
    - sudo ln -s $(pwd)/rootfs-trusty-arm64/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu
    # note: do not try this at home, see servo/servo#9579
    - sudo rm /usr/bin/ld.gold

  # Android
  - os: linux
    env:
    - BUILD_TARGET=android TRIPLET=arm-linux-androideabi
    before_script:
    - source setup_android.sh
    script:
    - git clone https://github.com/servo/servo --depth=1
    - cd servo
    - ./mach build --rel --android

  # OSX
  - os: osx
    before_script:
    - brew install automake pkg-config python cmake openssl
    - brew link --force openssl
    - pip install virtualenv
    env:
    - BUILD_TARGET=x86_64-apple-darwin TRIPLET=x86_64-apple-darwin
    script:
    - git clone https://github.com/servo/servo --depth=1
    - cd servo
    - ./mach build -r

script:
  - export CC=$TRIPLET-gcc
  - export CXX=$TRIPLET-g++
  - export PATH="$PATH:$HOME/bin"
  - git clone https://github.com/servo/servo --depth=10
  - sed -i "s/stdlibs = \[host_triple(), \"arm-linux-androideabi\"\]/stdlibs = set(\[host_triple(), \"arm-linux-androideabi\", \"$BUILD_TARGET\"\])/" servo/python/servo/bootstrap_commands.py
  - cd servo
  - ./mach build --rel --target=$BUILD_TARGET

after_success:
  - cd $TRAVIS_BUILD_DIR/servo
  - export ASSET_NAME=servo_${TRIPLET}_$(date '+%Y-%m-%d').tgz
  - if [[ "$BUILD_TARGET" == "android" ]]; then ./mach package --release; fi
  - if [[ "$BUILD_TARGET" == "android" ]]; then tar czf $ASSET_NAME --transform 's|target/'$TRIPLET'/release/||' target/$TRIPLET/release/servo.apk resources; fi
  - if [[ "$BUILD_TARGET" != "android" ]]; then tar czf $ASSET_NAME --transform 's|target/'$BUILD_TARGET'/release/||' target/$BUILD_TARGET/release/servo target/$BUILD_TARGET/release/libservo.rlib resources; fi
  - cd ..
  - ./upload_to_github.py
